# frozen_string_literal: true

remove_default_rails_layers(
  "app/controllers",
  "app/helpers",
  "app/mailers"
)

create_directory_tree(
  [
    "app/domains",
    "app/domains/shared",
    "app/domains/authentication",
    "app/domains/authentication/users",
    "app/domains/authentication/users/models",
    "app/domains/authentication/users/services",
    "app/domains/authentication/users/repositories",
    "app/domains/authentication/users/events",
    "app/domains/authentication/profiles",
    "app/domains/authentication/profiles/models",
    "app/domains/authentication/profiles/services",
    "app/domains/authentication/profiles/repositories",
    "app/domains/authentication/profiles/events",
    "app/domains/authentication/roles",
    "app/domains/authentication/roles/models",
    "app/domains/authentication/roles/services",
    "app/domains/authentication/roles/repositories",
    "app/domains/authentication/roles/events",
    "app/domains/authentication/permissions",
    "app/domains/authentication/permissions/models",
    "app/domains/authentication/permissions/services",
    "app/domains/authentication/permissions/repositories",
    "app/domains/authentication/permissions/events",
    "app/models",
    "app/interfaces/http/controllers",
    "app/interfaces/http/controllers/authentication",
    "app/interfaces/http/forms",
    "app/interfaces/http/forms/authentication",
    "app/interfaces/http/presenters",
    "app/interfaces/http/presenters/authentication",
    "app/interfaces/http/views",
    "app/interfaces/http/views/authentication",
    "app/infrastructure",
    "app/shared"
  ]
)

create_keep_files(
  [
    "app/domains/.keep",
    "app/domains/shared/.keep",
    "app/domains/authentication/.keep",
    "app/domains/authentication/users/models/.keep",
    "app/domains/authentication/users/services/.keep",
    "app/domains/authentication/users/repositories/.keep",
    "app/domains/authentication/users/events/.keep",
    "app/domains/authentication/profiles/models/.keep",
    "app/domains/authentication/profiles/services/.keep",
    "app/domains/authentication/profiles/repositories/.keep",
    "app/domains/authentication/profiles/events/.keep",
    "app/domains/authentication/roles/models/.keep",
    "app/domains/authentication/roles/services/.keep",
    "app/domains/authentication/roles/repositories/.keep",
    "app/domains/authentication/roles/events/.keep",
    "app/domains/authentication/permissions/models/.keep",
    "app/domains/authentication/permissions/services/.keep",
    "app/domains/authentication/permissions/repositories/.keep",
    "app/domains/authentication/permissions/events/.keep",
    "app/models/.keep",
    "app/interfaces/http/controllers/.keep",
    "app/interfaces/http/controllers/authentication/.keep",
    "app/interfaces/http/forms/.keep",
    "app/interfaces/http/forms/authentication/.keep",
    "app/interfaces/http/presenters/.keep",
    "app/interfaces/http/presenters/authentication/.keep",
    "app/interfaces/http/views/.keep",
    "app/interfaces/http/views/authentication/.keep",
    "app/infrastructure/.keep"
  ]
)
